### ISSUE TITLE
Grid support

### ISSUE THREAD

**Issue by lencioni** [robinweser/inline-style-prefixer#173]
According to #172 and a quick review of the code here, it looks like there is no special support for grid yet. I'm opening this issue to track the addition of this feature to inline-style-prefixer.

Here's a useful article from last year that details the translations autoprefixer does to support grid: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

Here are the autoprefixer test cases (looks like there are a lot for grid): https://github.com/postcss/autoprefixer/tree/master/test/cases

**Comment by ignorabilis** [comment]
We need that functionality too - without it grid is practially unusable in IE 11.
