### ISSUE TITLE
The backgroundClip is missing in plugins

### ISSUE THREAD

**Issue by ubRoman** [robinweser/inline-style-prefixer#226]
Getting following error with version 6.0.2 in my project:
`@parcel/core: Failed to resolve 'inline-style-prefixer/lib/plugins/backgroundClip' from './node_modules/react-native-web/dist/modules/prefixStyles/static.js'`

Indeed the backgroundClip is not there. Is it a new design or just a bug?

**Comment by jamaybyrone** [comment]
It appears to have been removed during: https://github.com/robinweser/inline-style-prefixer/pull/225

**Comment by jamaybyrone** [comment]
@ubRoman I've just downgraded react-native-web to get around it for now.

**Comment by ubRoman** [comment]
@jamaybyrone  Strange things happens at my site. In my lib, which uses react-native-web, its dependency of `inline-style-prefixer` has the version 6.0.2, but in a project, where this lib is used and react-native-web is also used directly, it is 6.0.1. Both react-native-web are of the last version 0.18.10. I have cleared npm cash on both projects and reinstalled node_modules completely. But still - in consumer project it is 6.0.1, in lib project 6.0.2. How is that? How can have two same versions of react-native-web different `inline-style-prefixer` versions as a dependency?

Yeah, probably I will downgrade react-native-web too.
