### ISSUE TITLE
Can't resolve 'inline-style-prefixer/lib/plugins/backgroundClip

### ISSUE THREAD

**Issue by oliviercperrier** [robinweser/inline-style-prefixer#227]
I'm currently running an expo project and i get this error when using the last version of inline-style-prefixer.

Is backgroundClip expected to be removed?

Thanks

`ERROR in ../packages/ui/node_modules/react-native-web/dist/modules/prefixStyles/static.js
Module not found: Error: Can't resolve 'inline-style-prefixer/lib/plugins/backgroundClip'`

**Comment by azigler** [comment]
I'm getting this same error now as of this morning, latest commit.

**Comment by robinweser** [comment]
@oliviercperrier @azigler When doing versioning I only thought about the main public API but didn't really consider clients using custom prefixing solutions.

I shipped a fix with `6.0.4` introducing a no-op plugin just to prevent clients from breaking. Another `7.0.0` release does the actual cleanup to get rid of the plugin.

**Comment by robinweser** [comment]
I'm closing this, if you keep having issues, please re-open and ping me. Sorry for the inconvenience.

**Comment by robinweser** [comment]
Additionally, also going to send a PR over at `react-native-web` to get rid of it already.

**Comment by azigler** [comment]
@robinweser Looks like it exists and just needs a merge: https://github.com/necolas/react-native-web/pull/2427
